
//Write a js program to find maximum between two numbers.//
//  ----------------------------------------------------

// var num1= +prompt("Enter you 1st number");
// var num2= +prompt("Enter your 2nd numbber");
// switch (num1>num2) {
//     case x:
//         console.log(num1);
//      break;
//      case y:
//          console.log(num2);
//      break;
//   }

  //    ---------------------------------------------------------------------------------//

  //Write a js program to find maximum between three numbers.//
  //    ---- -----------------------------------                                                                                                                                                                                                                     

  
// var num1 = parseFloat(prompt("Enter first number: "));
// var num2 = parseFloat(prompt("Enter second number: "));
// var num3 = parseFloat(prompt("Enter third number: "));
// let largest;

// if(num1 >= num2 && num1 >= num3) {
//     largest = num1;
// }
// else if (num2 >= num1 && num2 >= num3) {
//     largest = num2;
// }
// else {
//     largest = num3;
// }

// // display the result
// console.log("The largest number is " + largest);

//  -----------------------------------------------------------------------------------//
//Write a js program to check whether a number is negative, positive or zero.//

// const number = parseInt(prompt("Enter a number: "));

// // check if number is greater than 0
// if (number > 0) {
//     console.log("The number is positive");
// }

// // check if number is 0
// else if (number == 0) {
//   console.log("The number is zero");
// }

// // if number is less than 0
// else {
//      console.log("The number is negative");
// }

//  -----------------------------------------------------------------------------------//

//Write a js program to check whether a number is divisible by 5 and 11 or not.//
// var num=+prompt("Enter your number");
// if (num%5==0) {
//     console.log("number is divisible 5", num);
//     if (num%5!==0) {
//         console.log("Number is not divisble 5")
//     }

//     if(num%11==0){
//         console.log("number is divisible 11",num)
//     }
//     if (num%11!==0) {
//         console.log("Number is not divisble 11")
//     }
   
// }
//  -----------------------------------------------------------------------------------//
//Write a js program to check whether a number is even or odd.//

// var num=+prompt('Enter you number');
// if (num%2==0) {
//     console.log("Number is even");
// } else {
//     console.log("Number is odd");
// }
//  ------------------------------------------------------------------------------------//
//Write a js program to check whether a year is leap year or not.//

// function checkLeapYear(year) {

//     //three conditions to find out the leap year
//     if ((0 == year % 4) && (0 != year % 100) || (0 == year % 400)) {
//         console.log(year + ' is a leap year');
//     } else {
//         console.log(year + ' is not a leap year');
//     }
// }

// // take input
// var year = +prompt('Enter a year:');

// checkLeapYear(year);
//  -----------------------------------------------------------------------------------------//

// // var chr=prompt("enter your chracter")
// // if ((chr >= 'a' && chr <= 'z') || (chr >= 'A' && chr <= 'Z')) {
// //     console.log("It is a chracter")
    
// // } 
// // else {
//     consol.log("it is not a chracter")
// }

//  ---------------------------------------------------------------------------------------//
// Write a js program to input any alphabet and check whether it is vowel or consonant


// var ch=prompt("Enter your wors")
// if ((ch == 'a' || ch == 'e' || ch == 'i' || ch == 'o' || ch == 'u' )) {
//     console.log("This vowel")
// } else {
//     console.log("This is consonant")
// }

//  ---------------------------------------------------------------------------------------//
// var ch=prompt("Enter your value")

// if((ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z')) {

//    console.log("Your vaue is AlPHABET")

// } else if(ch >= '0' && ch <= '9') {

//     console.log("Your vaue is DIGIT")

// } else {

//     console.log("Your vaue is Special Chracter")

// }

//  ---------------------------------------------------------------------------------------------//

//Write a js program to find length of a string//
// var str = "Hello World!";
// var n =console.log (str.length);
//  ---------------------------------------------------------------------------------------------//
//Write a js program to copy one string to another string.//
// const str = "apple";

// const copy = str.slice();

// console.log(copy);
//  ----------------------------------------------------------------------------------------------//
//Write a js program to concatenate two strings.//

// var str1="Faisal"
// var str2="Saeed"
// var result=str1.concat(str2);
// console.log("your result is", result);

//  ---------------------------------------------------------------------------------------------------


    